name: ${COMPOSE_PROJECT_NAME}-webapp

services:
  webapp:
    container_name: ${COMPOSE_PROJECT_NAME}-webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${WEBAPP_PORT}:8080
    deploy:
      restart_policy:
        condition: any
        delay: 5s
#        max_attempts: 3
        window: 30s
      resources:
        limits:
          cpus: '3'
          memory: 3G